# Generated by Django 3.2 on 2022-05-14 12:09

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220504_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='link',
            new_name='github',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='skills',
        ),
        migrations.AddField(
            model_name='project',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=base.models.get_profile_image),
        ),
        migrations.AddField(
            model_name='project',
            name='site',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='skill_set',
            field=models.ManyToManyField(blank=True, related_name='skill_set', to='base.Skill'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='skills',
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='skill', to='base.Skill'),
        ),
    ]
