# Generated by Django 3.2 on 2022-05-14 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220514_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='profile_image',
            new_name='project_image',
        ),
    ]
